# Generated by Django 5.0.3 on 2024-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('image_ai', models.ImageField(blank=True, null=True, upload_to='mediaai')),
            ],
            options={
                'verbose_name': 'Imageai',
                'verbose_name_plural': 'Obrazy AI',
            },
        ),
    ]
